title: Nom de Mon Site
email: votre.email@example.com
description: >- # Ceci est une description longue pour votre site.
  Bienvenue sur mon blog personnel. Ici, je partage mes pensées, mes articles et bien plus encore.
baseurl: "" # le sous-chemin de votre site, e.g., "/blog" si votre site est à example.com/blog
url: "http://votre-nom-de-domaine.com" # l'URL de votre site

# Build settings
markdown: kramdown
theme: minima

# Metadonnées supplémentaires
author: AK
twitter_username: votre_nom_d'utilisateur_twitter
github_username:  votre_nom_d'utilisateur_github

# Options de menu
header_pages:
  - index.md
  - about.md
  - contact.md

# Footer settings
footer: © {{ site.time | date: '%Y' }} {{ site.title }}. Tous droits réservés.